### PR TITLE
fix: don't crash replica audit reload when forwarding URLs are unset

### LINKED ISSUE #1265: Replica crashes during audit logging when RS_PRIMARY_URL / RS_SECONDARY_URL are not set
## Summary
A read-only replica crashes during startup/audit logging when forwarding URLs are not configured.  
If `RS_PRIMARY_URL` and `RS_SECONDARY_URL` are unknown/unset, the instance should keep running and emit a warning that audit messages will not be forwarded.

## Steps to reproduce
1. Start ReductStore in replica mode (read-only) without setting forwarding URLs (`RS_PRIMARY_URL` / `RS_SECONDARY_URL`).
2. Launch the instance with an empty data path / no `$audit` bucket.

## Expected behavior
- Instance should **not crash**.
- It should log a warning indicating audit messages cannot be forwarded because primary/secondary URLs are unknown or unset.
- Service should continue operating in replica mode.

## Actual behavior
The instance panics and crashes:

thread 'tokio-rt-worker' (10) panicked at /home/runner/.cargo/git/checkouts/reductstore-0983dd190f4f924f/e05e3d6/reductstore/src/storage/engine/read_only.rs:64:21:
Failed to load bucket from "/data/$audit": [InternalServerError] No such file or directory (os error 2)

## Environment
- ReductStore PRO: `1.19.0` (`cd307f0`, built `2026-03-31T14:55:10Z`)
- ReductStore Core: `1.19.0` (`e05e3d6`, built `2026-03-31T14:54:29Z`)
- Branch: `main`
- OS: Linux
- Role: `RS_INSTANCE_ROLE=REPLICA`

## Logs
```
reductstore_pro/main.rs:11 ReductStore PRO 1.19.0 [cd307f0 at 2026-03-31T14:55:10Z]
2026-03-31 15:02:13.846 (78016) [INFO] -- reductstore/launcher.rs:27 ReductStore Core 1.19.0 [e05e3d6 at 2026-03-31T14:54:29Z]
...
thread 'tokio-rt-worker' (10) panicked at /home/runner/.cargo/git/checkouts/reductstore-0983dd190f4f924f/e05e3d6/reductstore/src/storage/engine/read_only.rs:64:21:
Failed to load bucket from "/data/$audit": [InternalServerError] No such file or directory (os error 2)
```

### PR DESCRIPTION
**Pull request by mother-6000**
Closes #1265

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix

### What was changed?

- Updated replica bucket reload logic to avoid panicking when loading `$audit` fails in read-only replica mode and neither `RS_PRIMARY_URL` nor `RS_SECONDARY_URL` is configured.
- Added a warning log explaining that audit messages will not be forwarded when both forwarding URLs are unset.
- Kept existing panic behavior for all other bucket restore failures.
- Added a regression test: `test_skip_broken_audit_bucket_without_primary_and_secondary_urls`.

### Related issues

- https://github.com/reductstore/reductstore/issues/1265

### Does this PR introduce a breaking change?

No.

### Other information:

Validation:
- `cargo test -p reductstore storage::engine::read_only::tests:: -- --nocapture`

### CODE REVIEW

File: reductstore/src/storage/engine/read_only.rs [hunk 1]
```diff
@@ -61,6 +63,21 @@ impl ReadOnlyMode for StorageEngine {
                     new_buckets.insert(bucket.name().to_string(), bucket);
                 }
                 Err(e) => {
+                    let bucket_name = path
```
Comment (atimin) [inline reductstore/src/storage/engine/read_only.rs]: it's a bad place to do. Print message from the configuration parser at the engine start.

Comment (mother-6000) [reply reductstore/src/storage/engine/read_only.rs]: Good point — moved this warning to startup config parsing.

Now we log once at engine start (Replica + both RS_PRIMARY_URL/RS_SECONDARY_URL unset), and keep reload logic focused on skipping the broken `$audit` restore path without inline warning noise.

Also kept the no-crash behavior for this scenario.

File: reductstore/src/storage/engine/read_only.rs [hunk 2]
```diff
@@ -61,7 +62,18 @@ impl ReadOnlyMode for StorageEngine {
...
+                        .file_name()
+                        .and_then(|name| name.to_str())
+                        .is_some_and(|bucket_name| {
+                            bucket_name == AUDIT_BUCKET_NAME
+                                && self.cfg.primary_url.is_none()
+                                && self.cfg.secondary_url.is_none()
+                        });
+
+                    if !skip_broken_audit_bucket {
+                        panic!("Failed to load bucket from {:?}: {}", path, e);
```
Comment (atimin) [inline reductstore/src/storage/engine/read_only.rs]: i think this is an issue unrelated to $audit . Don't check the name and urls. Just print an error log message. We can't panic here.

Comment (mother-6000) [reply reductstore/src/storage/engine/read_only.rs]: Good call — I removed the `$audit`/URL-specific branch from reload.

Now any bucket restore failure in replica reload is handled uniformly: we log an error and continue, without panic. This keeps reload resilient regardless of bucket name or forwarding configuration.

**Review by atimin — APPROVED** [review]
