### PR TITLE
Fix directive parsing and order of operators in conditional query

### LINKED ISSUE #894: Bug: Context directives and $limit operator  don't work together
### What happened?

When I use context directives and the $limit operator together in a query, I don't get any results:

```json
{
  "#ctx_before": "5s",
  "$each_t": "10m",
  "$or": [
    {
      "$not": [
        {
          "$has": "prod_speed"
        }
      ]
    },
    {
      "&prod_speed": {
        "$gt": -1
      }
    }
  ],
  "&status": {
    "$eq": 0
  },
  "$limit": 10
}

```

### Version

v1.16.0

### OS

Linux

### Snippet to repeat the bug

_No response_

### Logs

```Shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by atimin**
Closes #894

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix + refactoring

### What was changed?

The query parser broke the order of operators after directive parsing.   The PR fixes this by preserving the order of operators. Additionally, it refactors the parser and moves the directive checks to the directives modules.

### Related issues

#894 #866 #888

### Does this PR introduce a breaking change?

No

### CODE REVIEW

File: reductstore/src/storage/query/condition/parser.rs [hunk 1]
```diff
@@ -99,24 +72,34 @@ impl Parser {
...
+                }
+                directives.insert(key.to_string(), parsed_values);
                 keys_to_remove.push(key.to_string());
             }
         }
 
         // Remove directives from the original JSON object
         for key in keys_to_remove {
-            json.as_object_mut().unwrap().remove(&key);
+            json.as_object_mut().unwrap().shift_remove(&key);
```
Comment (atimin) [inline reductstore/src/storage/query/condition/parser.rs:102]: @AnthonyCvn FIY, this part broke the order. If a query had a directive, this method was called and it shuffled the operators in the query.
