### PR TITLE
Fix primary-mode Ctrl-C shutdown lock-file cleanup

### LINKED ISSUE #1246: ReductStore in Primary mode does not release lock file on Ctrl-C shutdown
### Summary
When ReductStore runs with `RS_INSTANCE_ROLE=primary`, shutting down via `Ctrl-C` hangs and reports a lock-file removal error.

### Steps to reproduce
1. Start ReductStore with `RS_INSTANCE_ROLE=primary`.
2. Stop the server with `Ctrl-C`.

### Expected behavior
ReductStore should stop immediately without errors.

### Actual behavior
Shutdown hangs, then logs:
`Failed to remove lock file: ReductError { status: InternalServerError, message: "No such file or directory (os error 2)" }`

### Environment
- ReductStore: `v1.19.0` (`main`, `c44bb395`, `2026-03-25T13:22:00Z`)
- OS: Linux

### Logs
```text
2026-03-25 13:28:40.213 (40128) [INFO] -- reductstore/launcher.rs:27 ReductStore Core 1.19.0 [c44bb395 at 2026-03-25T13:22:00Z]
2026-03-25 13:28:40.228 (40128) [WARN] -- reductstore/cfg/provision/token.rs:115 Token 'token' has no value. Drop it.
2026-03-25 13:28:40.228 (40128) [INFO] -- reductstore/cfg.rs:295 Configuration:
 RS_API_BASE_PATH = / (default)
 RS_HOST = 0.0.0.0 (default)
 RS_PORT = 8383 (default)
 RS_PUBLIC_URL = http://0.0.0.0:8383/ (default)
 RS_INSTANCE_ROLE = primary
 RS_DATA_PATH = /tmp/data1/
 RS_REPLICATION_1_NAME = test
 RS_REPLICATION_1_SRC_BUCKET = src
 RS_REPLICATION_1_DST_BUCKET = dst
 RS_REPLICATION_1_DST_HOST = http://127.0.0.1:8383
 RS_REPLICATION_1_MODE = disabled
 RS_LOG_LEVEL = INFO,reductstore/api=DEBUG
 RS_CORS_ALLOW_ORIGIN = *
 RS_TOKEN_1_NAME_ = token
2026-03-25 13:28:40.228 (40128) [INFO] -- reductstore/cfg.rs:306 License: Apache-2.0 [https://github.com/reductstore/reductstore/blob/v1.19.0/LICENSE]
2026-03-25 13:28:40.229 (40128) [INFO] -- reductstore/launcher.rs:73 Public URL: http://0.0.0.0:8383/
2026-03-25 13:28:40.347 (24512) [INFO] -- reductstore/storage/engine.rs:95 Load 2 bucket(s) in 15.701307ms
2026-03-25 13:28:40.347 (24512) [INFO] -- reductstore/cfg.rs:429 Load Web Console
2026-03-25 13:28:40.685 (24512) [INFO] -- reductstore/cfg/provision/replication.rs:45 Provisioned replication 'test' with ReplicationSettings { src_bucket: "src", dst_bucket: "dst", dst_host: "http://127.0.0.1:8383/", dst_token: None, entries: [], include: {}, exclude: {}, each_n: None, each_s: None, when: None, mode: Disabled }
^C2026-03-25 13:28:42.979 ( 5920) [INFO] -- reductstore/launcher.rs:155 Received Ctrl-C, shutting down server...
2026-03-25 13:28:48.047 (40128) [INFO] -- reductstore/launcher.rs:150 Server has been shut down.
```

### PR DESCRIPTION
**Pull request by mother-6000**
Closes #1246

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix.

### What was changed?

- Made lock-file cleanup idempotent in `ImplLockFile`.
- Added a shared `released` atomic guard so cleanup runs only once across both explicit `release()` and `Drop` cleanup path.
- Added `remove_lock_file_once` helper that:
  - skips duplicate removal attempts,
  - treats `ErrorCode::NotFound` as successful cleanup,
  - keeps logging real removal failures.
- Added regression test `test_lock_file_release_is_idempotent` to verify repeated `release()` calls leave cleanup stable.

### Related issues

- https://github.com/reductstore/reductstore/issues/1246
- Approved implementation plan comment: https://github.com/reductstore/reductstore/issues/1246#issuecomment-4126672808

### Does this PR introduce a breaking change?

No.

### Other information:

- Attempted to run the new test locally, but the current container `cargo` cannot read this repository lockfile format (`Cargo.lock` version 4 requires `-Znext-lockfile-bump`).

### CODE REVIEW

File: reductstore/src/lock_file.rs [hunk 1]
```diff
@@ -41,6 +41,7 @@ pub type BoxedLockFile = Box<dyn LockFile + Sync + Send>;
 struct ImplLockFile {
     path: PathBuf,
     stop_on_drop: Arc<AtomicBool>,
+    released: Arc<AtomicBool>,
```
Comment (atimin) [inline reductstore/src/lock_file.rs]: I have a better idea. Instead of overcomplicating it, remove the release method from the trait. We only rely on the drop since the lock file lives until the end of the program. Use blocks for tests to release the lock file.

**Review by atimin — CHANGES_REQUESTED** [review]

File: reductstore/src/lock_file.rs (hunk 1 above)
Comment (mother-6000) [reply reductstore/src/lock_file.rs]: Done in this PR: removed `release` from the `LockFile` trait, switched tests to scope-based drop cleanup, and added a coverage test for the already-removed lock-file path (`test_remove_lock_file_when_already_removed`). This keeps lock lifecycle drop-driven as suggested.

Comment (mother-6000) [reply reductstore/src/lock_file.rs]: Follow-up pushed in commit f19d095: simplified lock-file cleanup to a single error path (`remove_lock_file` logs on removal failure) while keeping the drop-driven lifecycle you requested. CI is now green, including Docker build and Codecov patch.
